name: Publish NPM Package

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Ensures your package is working correctly

      - name: Publish to NPM
        if: success()  # Only runs if tests pass
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
